export const CommandIds = {
  checkAccessibility: 'codespeak.checkAccessibility',
  clearApiKey: 'codespeak.clearApiKey',
  clearAccessibilityFindings: 'codespeak.clearAccessibilityFindings',
  explainDiagnostic: 'codespeak.explainDiagnostic',
  explainSelection: 'codespeak.explainSelection',
  generateCode: 'codespeak.generateCode',
  generateDocumentation: 'codespeak.generateDocumentation',
  summarizeFile: 'codespeak.summarizeFile',
  summarizeFolder: 'codespeak.summarizeFolder',
  summarizeWorkspace: 'codespeak.summarizeWorkspace',
  goToLine: 'codespeak.goToLine',
  listDiagnostics: 'codespeak.listDiagnostics',
  openFile: 'codespeak.openFile',
  redo: 'codespeak.redo',
  readCodeStructure: 'codespeak.readCodeStructure',
  selectAccessibilityProfile: 'codespeak.selectAccessibilityProfile',
  setApiKey: 'codespeak.setApiKey',
  speakSelection: 'codespeak.speech.speakSelection',
  stopSpeaking: 'codespeak.speech.stop',
  undo: 'codespeak.undo',
  voiceStartContinuous: 'codespeak.voice.startContinuous',
  voiceStopContinuous: 'codespeak.voice.stopContinuous',
  voiceToggle: 'codespeak.voice.toggle',
} as const;
