import { CommandIds } from './command-ids';

export interface CodeSpeakCommandDefinition {
  readonly id: string;
  readonly displayName: string;
  readonly voiceAliases: readonly string[];
  readonly description: string;
  readonly requiresEditor: boolean;
  readonly requiresSelection: boolean;
  readonly producesSpeech: boolean;
  readonly requiresConfirmation: boolean;
}

export const CODE_SPEAK_COMMANDS: readonly CodeSpeakCommandDefinition[] = [
  definition(
    CommandIds.toggleDyslexiaMode,
    'Toggle Dyslexia Mode',
    [
      'enable dyslexia mode',
      'turn on dyslexia mode',
      'disable dyslexia mode',
      'turn off dyslexia mode',
      'toggle dyslexia mode',
    ],
    'Enable or disable the reversible Dyslexia Mode profile.',
    false,
    false,
    true,
  ),
  definition(
    CommandIds.configureDyslexiaMode,
    'Configure Dyslexia Mode',
    ['configure dyslexia mode', 'change dyslexia settings'],
    'Change one Dyslexia Mode reading preference.',
    false,
    false,
    true,
  ),
  definition(
    CommandIds.configureDyslexiaFont,
    'Configure Dyslexia font',
    ['change dyslexia font', 'configure dyslexia font'],
    'Choose a preferred installed font with safe fallbacks.',
    false,
    false,
    true,
  ),
  definition(
    CommandIds.openDyslexiaSetup,
    'Open Dyslexia Mode setup instructions',
    ['open dyslexia setup', 'show dyslexia setup instructions'],
    'Open accessible font and Dyslexia Mode setup guidance.',
    false,
    false,
    true,
  ),
  definition(
    CommandIds.toggleDyslexiaFocusMode,
    'Toggle Dyslexia Focus Mode',
    ['turn on focus reading', 'turn off focus reading', 'toggle dyslexia focus mode'],
    'Temporarily use the native VS Code focused editor layout.',
    false,
    false,
    true,
  ),
  definition(
    CommandIds.explainCurrentErrorSimply,
    'Explain current error simply',
    ['explain current error simply', 'explain this error simply'],
    'Explain the current diagnostic with short plain language steps.',
    true,
    false,
    true,
  ),
  definition(
    CommandIds.explainSelectedCodeSimply,
    'Explain selected code simply',
    ['explain selected code simply', 'explain this simply'],
    'Explain selected code with short plain language steps.',
    true,
    false,
    true,
  ),
  definition(
    CommandIds.simplifyExplanation,
    'Simplify this explanation',
    ['simplify this explanation', 'make this explanation simpler'],
    'Rewrite selected explanatory text in a simpler format.',
    true,
    false,
    true,
  ),
  definition(
    CommandIds.explainCurrentLineSimply,
    'Explain current line',
    ['explain current line'],
    'Explain only the current line in simple language.',
    true,
    false,
    true,
  ),
  definition(
    CommandIds.explainCurrentBlockSimply,
    'Explain current block',
    ['explain current block'],
    'Explain the smallest current code block.',
    true,
    false,
    true,
  ),
  definition(
    CommandIds.explainCurrentFunctionSimply,
    'Explain current function simply',
    ['explain current function simply'],
    'Explain the current function in small labeled chunks.',
    true,
    false,
    true,
  ),
  definition(
    CommandIds.summarizeFileSimply,
    'Summarize file in simple language',
    ['summarize file in simple language', 'summarize this file simply'],
    'Summarize the active file using short plain language sections.',
    true,
    false,
    true,
  ),
  definition(
    CommandIds.breakCodeIntoSteps,
    'Break code into steps',
    ['break code into steps', 'explain code step by step'],
    'Describe selected or current code as a short sequence.',
    true,
    false,
    true,
  ),
  definition(
    CommandIds.readAmbiguousCharacters,
    'Read ambiguous characters',
    ['read ambiguous characters', 'identify confusing characters'],
    'Identify commonly confused characters in the line or selection.',
    true,
    false,
    true,
  ),
  definition(
    CommandIds.voiceCancelCurrent,
    'Cancel current voice command',
    ['cancel current voice command', 'stop current voice command', 'discard voice command'],
    'Discard active listening or abort the voice command currently being processed.',
    false,
    false,
    true,
  ),
  definition(
    CommandIds.showAccessibleControls,
    'Show accessible controls',
    ['show accessible controls', 'open accessible controls'],
    'Choose common CodeSpeak actions from a native accessible picker.',
    false,
    false,
    true,
  ),
  definition(
    CommandIds.explainSelection,
    'Explain selected code',
    ['explain selected code', 'what does this selection do', 'explain it'],
    'Explain selected code or the current context.',
    true,
    false,
    true,
  ),
  definition(
    CommandIds.explainCurrentFunction,
    'Explain current function',
    ['explain current function'],
    'Explain the function containing the cursor.',
    true,
    false,
    true,
  ),
  definition(
    CommandIds.generateDocumentation,
    'Document selection',
    ['document this selection', 'document selected code'],
    'Generate documentation for selected code.',
    true,
    true,
    true,
    true,
  ),
  definition(
    CommandIds.summarizeFile,
    'Summarize file',
    ['summarize this file', 'summarize file', 'code speak summarize file'],
    'Summarize the active file.',
    true,
    false,
    true,
  ),
  definition(
    CommandIds.readCodeStructure,
    'Read current function',
    ['read current function', 'read file structure'],
    'Read structural code information.',
    true,
    false,
    true,
  ),
  definition(
    CommandIds.checkAccessibility,
    'Scan accessibility',
    ['scan accessibility', 'check accessibility', 'run code speak accessibility scan'],
    'Scan the active JSX or TSX document.',
    true,
    false,
    true,
  ),
  definition(
    CommandIds.explainDiagnostic,
    'Explain current diagnostic',
    ['explain current diagnostic', 'explain current error'],
    'Explain a diagnostic in plain language.',
    true,
    false,
    true,
  ),
  definition(
    CommandIds.readSelectionContext,
    'Read selected code',
    ['read selected code', 'what is selected', 'read selection'],
    'Read the selected code with structural context.',
    true,
    false,
    true,
  ),
  definition(
    CommandIds.readSelectionDiagnostics,
    'Find errors in selection',
    ['find errors in this selection', 'find errors in selection'],
    'Read diagnostics intersecting the selected code.',
    true,
    false,
    true,
  ),
  definition(
    CommandIds.whereAmI,
    'Where am I',
    ['where am i', 'what function am i in'],
    'Announce the current editor location and context.',
    true,
    false,
    true,
  ),
  definition(
    CommandIds.readCurrentLine,
    'Read current line',
    ['read current line'],
    'Read the current editor line.',
    true,
    false,
    true,
  ),
  definition(
    CommandIds.readCurrentDiagnostic,
    'Read current error',
    ['read current error', 'read current diagnostic'],
    'Read diagnostics on the current line.',
    true,
    false,
    true,
  ),
  definition(
    CommandIds.readAllDiagnostics,
    'Read all errors',
    ['read all errors', 'read all diagnostics'],
    'Read a bounded workspace diagnostic summary.',
    false,
    false,
    true,
  ),
  definition(
    CommandIds.readNextDiagnostic,
    'Read next error',
    ['read next error', 'go to next warning'],
    'Move to and read the next diagnostic.',
    false,
    false,
    true,
  ),
  definition(
    CommandIds.openFolder,
    'Open folder',
    ['open folder', 'open a folder', 'open the folder', 'open project folder'],
    'Open the native folder picker.',
    false,
    false,
    true,
  ),
  definition(
    CommandIds.openRecentFolder,
    'Open recent folder',
    ['open recent folder', 'open the first recent project'],
    'Open the native recent projects picker.',
    false,
    false,
    true,
  ),
  definition(
    CommandIds.askCopilot,
    'Ask Copilot',
    ['ask copilot', 'open copilot chat'],
    'Open GitHub Copilot Chat with contextual guidance.',
    false,
    false,
    true,
  ),
  definition(
    CommandIds.listVoiceCommands,
    'List voice commands',
    [
      'list code speak commands',
      'show code speak commands',
      'what can i say',
      'voice command examples',
      'help',
    ],
    'Read available commands in small groups.',
    false,
    false,
    true,
  ),
  definition(
    CommandIds.nextVoiceCommands,
    'Next voice commands',
    ['next commands', 'continue commands'],
    'Read the next group of available voice commands.',
    false,
    false,
    true,
  ),
  definition(
    CommandIds.startFocusTimer,
    'Start focus timer',
    ['start focus timer', 'start pomodoro'],
    'Start a focus session.',
    false,
    false,
    true,
  ),
  definition(
    CommandIds.toggleFocusView,
    'Toggle focus view',
    ['toggle focus view', 'enter focus view', 'exit focus view', 'hide distractions'],
    'Toggle the distraction reducing VS Code Zen Mode layout.',
    false,
    false,
    true,
  ),
  definition(
    CommandIds.askLearningQuestion,
    'Ask a learning question',
    ['ask a learning question'],
    'Open an accessible programming lesson.',
    false,
    false,
    true,
  ),
  definition(
    CommandIds.clearApiKey,
    'Clear Gemini API key',
    ['clear gemini api key'],
    'Remove the stored Gemini key.',
    false,
    false,
    true,
    true,
  ),
  definition(
    CommandIds.clearOpenAiApiKey,
    'Clear OpenAI API key',
    ['clear open ai api key', 'clear openai api key'],
    'Remove the stored primary OpenAI key.',
    false,
    false,
    true,
    true,
  ),
  definition(
    CommandIds.clearAccessibilityFindings,
    'Clear accessibility findings',
    ['clear accessibility findings'],
    'Clear CodeSpeak Problems entries.',
    false,
    false,
    true,
    true,
  ),
  definition(
    CommandIds.generateCode,
    'Generate code',
    ['generate code', 'create code'],
    'Generate code from a spoken instruction.',
    true,
    false,
    true,
    true,
  ),
  definition(
    CommandIds.summarizeFolder,
    'Summarize folder',
    ['summarize folder'],
    'Summarize the active folder.',
    true,
    false,
    true,
  ),
  definition(
    CommandIds.summarizeWorkspace,
    'Summarize workspace',
    ['summarize workspace', 'summarize project'],
    'Summarize representative workspace files.',
    false,
    false,
    true,
  ),
  definition(CommandIds.goToLine, 'Go to line', [], 'Move to a line number.', true, false, true),
  definition(
    CommandIds.listDiagnostics,
    'Navigate diagnostics',
    ['navigate diagnostics', 'list diagnostics'],
    'Choose a workspace diagnostic.',
    false,
    false,
    true,
  ),
  definition(
    CommandIds.nextDiagnostic,
    'Go to next diagnostic',
    ['go to next diagnostic'],
    'Move to the next Problems entry.',
    false,
    false,
    false,
  ),
  definition(
    CommandIds.previousDiagnostic,
    'Go to previous diagnostic',
    ['go to previous diagnostic'],
    'Move to the previous Problems entry.',
    false,
    false,
    false,
  ),
  definition(
    CommandIds.openFile,
    'Open workspace file',
    ['open file'],
    'Find and open a workspace file.',
    false,
    false,
    true,
  ),
  definition(
    CommandIds.pauseFocusTimer,
    'Pause focus timer',
    ['pause focus timer'],
    'Pause the current focus session.',
    false,
    false,
    true,
  ),
  definition(
    CommandIds.resetFocusTimer,
    'Reset focus timer',
    ['reset focus timer'],
    'Reset the focus session.',
    false,
    false,
    true,
  ),
  definition(
    CommandIds.redo,
    'Redo',
    ['redo', 'redo that'],
    'Redo the last editor action.',
    true,
    false,
    true,
    true,
  ),
  definition(
    CommandIds.readNextLine,
    'Read next line',
    ['read next line'],
    'Move to and read the next line.',
    true,
    false,
    true,
  ),
  definition(
    CommandIds.readPreviousLine,
    'Read previous line',
    ['read previous line'],
    'Move to and read the previous line.',
    true,
    false,
    true,
  ),
  definition(
    CommandIds.selectAccessibilityProfile,
    'Select accessibility profile',
    ['select accessibility profile', 'run code speak blind mode', 'activate blind mode'],
    'Choose an accessibility profile.',
    false,
    false,
    true,
  ),
  definition(
    CommandIds.setApiKey,
    'Set Gemini API key',
    ['set gemini api key'],
    'Store a Gemini key securely.',
    false,
    false,
    true,
  ),
  definition(
    CommandIds.setOpenAiApiKey,
    'Set OpenAI API key',
    ['set open ai api key', 'set openai api key'],
    'Store the primary OpenAI key securely.',
    false,
    false,
    true,
  ),
  definition(
    CommandIds.speakSelection,
    'Read selection aloud',
    ['speak selection'],
    'Read selected text aloud.',
    true,
    true,
    true,
  ),
  definition(
    CommandIds.stopSpeaking,
    'Stop reading aloud',
    ['stop reading'],
    'Stop speech output.',
    false,
    false,
    true,
  ),
  definition(
    CommandIds.repeatSpeech,
    'Repeat last message',
    ['repeat that'],
    'Repeat the last spoken message.',
    false,
    false,
    true,
  ),
  definition(
    CommandIds.resumeSpeech,
    'Resume reading',
    ['continue', 'resume'],
    'Restart the paused spoken message.',
    false,
    false,
    true,
  ),
  definition(
    CommandIds.slowerSpeech,
    'Speak slower',
    ['speak slower', 'read slower'],
    'Reduce speech speed.',
    false,
    false,
    true,
  ),
  definition(
    CommandIds.fasterSpeech,
    'Speak faster',
    ['speak faster', 'read faster'],
    'Increase speech speed.',
    false,
    false,
    true,
  ),
  definition(
    CommandIds.pauseSpeech,
    'Pause reading',
    ['pause'],
    'Pause current speech output.',
    false,
    false,
    true,
  ),
  definition(
    CommandIds.undo,
    'Undo',
    ['undo', 'undo that'],
    'Undo the last editor action.',
    true,
    false,
    true,
    true,
  ),
  definition(
    CommandIds.voiceStartContinuous,
    'Start continuous voice mode',
    ['start continuous voice mode'],
    'Start continuous listening.',
    false,
    false,
    true,
  ),
  definition(
    CommandIds.voiceStopContinuous,
    'Stop continuous voice mode',
    ['stop continuous voice mode'],
    'Stop continuous listening.',
    false,
    false,
    true,
  ),
  definition(
    CommandIds.voiceSimulate,
    'Enter voice command as text',
    ['simulate voice command', 'test voice command'],
    'Run the exact Blind Mode voice pipeline without using a microphone.',
    false,
    false,
    true,
  ),
  definition(
    CommandIds.voiceToggle,
    'Toggle voice mode',
    ['toggle voice mode', 'start voice mode'],
    'Start or stop voice listening.',
    false,
    false,
    true,
  ),
];

function definition(
  id: string,
  displayName: string,
  voiceAliases: readonly string[],
  description: string,
  requiresEditor: boolean,
  requiresSelection: boolean,
  producesSpeech: boolean,
  requiresConfirmation = false,
): CodeSpeakCommandDefinition {
  return {
    id,
    displayName,
    voiceAliases,
    description,
    requiresEditor,
    requiresSelection,
    producesSpeech,
    requiresConfirmation,
  };
}

export function findCommandByVoiceAlias(
  transcript: string,
): CodeSpeakCommandDefinition | undefined {
  const normalized = normalizeVoiceText(transcript)
    .replace(/^run code speak /u, '')
    .replace(/^code speak /u, '');
  return CODE_SPEAK_COMMANDS.find((command) =>
    command.voiceAliases.some((alias) => normalizeVoiceText(alias) === normalized),
  );
}

export function normalizeVoiceText(value: string): string {
  return value
    .trim()
    .toLocaleLowerCase()
    .replace(/[.,!?]/gu, '')
    .replace(/\bcodespeak\b/gu, 'code speak')
    .replace(/\s+/gu, ' ');
}
